---
- hosts: local
  tasks:
    # - name: install EPEL
    #   shell: sudo rpm -Uvh --quiet http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm      
    #
    # - name: install Docker
    #   shell: sudo yum install docker-io
    #   notify: 
    #     - verify docker install

    - name: check if docker binary is already installed
      stat: path=/tmp/docker
      register: docker_exists 

    - name: install Docker binary
      shell: sudo wget https://get.docker.com/builds/Linux/x86_64/docker-latest -O /tmp/docker
      when: docker_exists.stat.exists == false

    - name: run chmod on docker
      shell: sudo chmod +x /tmp/docker

    - name: symlink docker
      shell: sudo ln -fs /tmp/docker /usr/bin/docker

    - name: create docker file in /etc/init.d
      template: src=/vagrant/docker.sh dest=/etc/init.d/docker

    - name: run chmod on the init.d file
      shell: sudo chmod +x /etc/init.d/docker

    - name: run docker daemon
      service: name=docker state=restarted
      notify:
        - verify docker install


  handlers:
    - name: verify docker install
      shell: sudo /usr/bin/docker info 
      register: cmd_result

    - assert:
        that:
          - "'comand not found' not in cmd_result.stderr"
